debug: TRUE

world-name: world
uhc-game-mode: TEAM
match-duration: 180

rules:
  - "&oWelcome to nerdUHC!"
  - "&7There are a few things of which you should be aware:"
  - "1) &7health does &oNOT&r&7 naturally regenerate."
  - "2) &7there are &4no protections&7 on chests, furnaces, etc."
  - "3) &7Ghasts love UHCs so much that they've stopped crying! &l&bGhast Tears&r&7 are unavailable."
  - "4) &7logging out during combat &nwill not save you&r&7. Keep an eye out for &6chickens&7..."
  - "5) &7PVP will enable approximately after &5Night 1&7."
  - "&7Most importantly, &lhave fun&r&7!"

spawn-x: 0
spawn-y: 65
spawn-z: 0

spawn-barrier-radius: 6
spawn-barrier-block-name: BARRIER

spread-distance-between-players: 200
spread-distance-from-spawn: 201
spread-respect-teams: TRUE

let-players-pick-teams: TRUE
force-even-teams: TRUE
max-team-size: 3
alive-team-name: ALIVE
dead-team-name: DEAD
allow-friendly-fire: FALSE

player-combat-tag-time-in-sec: 30
combat-tag-doppel: CHICKEN

do-deathmatch: TRUE
deathmatch-distance-between-players: 20
deathmatch-distance-from-spawn: 100

teams:
  - name: 'Sapphlings'
    color: 'RED'
  - name: 'Guardians'
    color: 'GOLD'
  - name: 'Blazes'
    color: 'YELLOW'
  - name: 'Creepers'
    color: 'GREEN'
  - name: 'Vexes'
    color: 'BLUE'
  - name: 'Endermen'
    color: 'DARK_PURPLE'

gamerules:
  - doDaylightCycle: true
  - NaturalRegeneration: false
  - doMobSpawning: true