health-display-slot: PLAYER_LIST
kills-display-slot: SIDEBAR
display-health-below-name: TRUE

default-uhc-mode: TEAM

let-players-pick-team: TRUE
force-even-teams: TRUE
teams-max-size: 3

teams:
  - Red
  - Orange
  - Yellow
  - Green
  - Blue
  - Purple
  
objectives:
  - name: 'health'
    criteria: 'health'
    displayslot: 'PLAYER_LIST'
  - name: 'healthoverhead'
    criteria: 'health'
    displayslot: 'BELOW_NAME'
  - name: 'kills'
    criteria: 'playerKillCount'
    displayslot: 'SIDEBAR'
  - name: 'deaths'
    criteria: 'deathCount'
    displayslot: 'none'