default-uhc-mode: SOLO

spawn-x: 0
spawn-y: 65
spawn-z: 0
spawn-barrier-radius: 6
spawn-barrier-block-name: BARRIER

spread-distance-between-players: 200
spread-distance-from-spawn: 201
spread-respect-teams: TRUE

let-players-pick-teams: TRUE
force-even-teams: TRUE
teams-max-size: 3
alive-team-name: ALIVE
dead-team-name: DEAD
teams:
  - name: 'Mooshroom Red'
    color: 'RED'
  - name: 'Guardian Orange'
    color: 'ORANGE'
  - name: 'Blaze Yellow'
    color: 'YELLOW'
  - name: 'Creeper Green'
    color: 'GREEN'
  - name: 'Vex Blue'
    color: 'BLUE'
  - name: 'Enderman Purple'
    color: 'PURPLE'

player-combat-tag-time-in-sec: 30
combat-tag-doppel: CHICKEN

gamerules:
  - doDaylightCycle: TRUE
  - NaturalRegeneration: FALSE

objectives:
  - name: 'kills'
    criteria: 'playerKillCount'
    displayslot: 'SIDEBAR'
  - name: 'deaths'
    criteria: 'deathCount'
    displayslot: 'none'
  - name: 'health'
    criteria: 'health'
    displayslot: 'PLAYER_LIST'
  - name: 'hp'
    criteria: 'health'
    displayslot: 'BELOW_NAME'