name: nerdUHC
main: com.bermudalocket.nerdUHC.NerdUHC
version: ${project.version}
permissions:
  nerduhc.gamemaster:
    description: Full permissions
    default: op
  nerduhc.basic:
    description: Base permission level for nerdUHC.
    default: true
commands:
  uhc:
    description: Command which controls current round
    usage: /uhc [start|stop]
    permission: nerduhc.gamemaster
    permission-message: You don't have permission to do that.
  join:
    description: Join a team.
    usage: /join [team]
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.
  t:
    description: Team chat
    usage: /t [msg]
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.
  sb-all:
    description: Refresh scoreboard for all players in match
    usage: /sb-all
    permission: nerduhc.gamemaster
    permission-message: You don't have permission to do that.
  fixme:
    description: Self-help command for players glitching out in spectator mode
    usage: /fixme
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.
  kit:
    description: Gives player a lobby kit
    usage: /kit
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.
  teamlist:
    description: List the current UHC teams.
    usage: /teamlist
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.
  rules:
    description: Prints a list of rules and tips to chat.
    usage: /rules
    permission: nerduhc.basic
    permission-message: You don't have permission to do that.