name: nerdUHC
main: com.bermudalocket.nerdUHC.NerdUHC
version: 1.0
commands:
  nerduhc:
    description: nerdUHC general command
    usage: /nerduhc
    permission: nerdUHC.basic
    permission-message: y u do that