name: nerdUHC
main: com.bermudalocket.nerdUHC.NerdUHC
version: 1.0
permissions:
  nerduhc.gamemaster:
    description: Full permissions
    default: op
  nerduhc.reload:
    description: Permission to reload nerdUHC configuration.
    default: op
  nerduhc.startpausestop:
    description: Permission to start, pause, and stop UHCs.
    default: op
  nerduhc.barrier:
    description: Permission to enable and disable the spawn barrier.
    default: op
  nerduhc.basic:
    description: Base permission level for nerdUHC.
    default: true
commands:
  barrier:
    description: Enables and disables the barrier around world's spawnpoint.
    usage: /barrier [on|off]
    permission: nerduhc.barrier
    permission-message: y u do that
  uhc:
    description: Command which controls starting, pausing, and stopping of current round
    usage: /uhc [start|pause|unpause|stop]
    permission: nerduhc.gamemaster
    permission-message: y u do that
  uhcreload:
    description: Reloads nerdUHC configuration
    usage: /uhcreload
    permission: nerduhc.reload
    permission-message: y u do that
  uhcmode:
    description: Changes the current or upcoming UHC's mode
    usage: /uhcmode [mode]
    permission: nerduhc.reload
    permission-message: y u do that
  join:
    description: Join a team.
    usage: /join [team]
    permission: nerduhc.basic
    permission-message: y u do that
  leave:
    description: Join a team.
    usage: /join [team]
    permission: nerduhc.basic
    permission-message: y u do that
  teamlist:
    description: List the current UHC teams.
    usage: /teamlist
    permission: nerduhc.basic
    permission-message: y u do that