name: nerdUHC
main: com.bermudalocket.nerdUHC.NerdUHC
version: 1.0
permissions:
  nerduhc.gamemaster:
    description: Full permissions
    default: op
  nerduhc.basic:
    description: Base permission level for nerdUHC.
    default: true
commands:
  barrier:
    description: Enables and disables the barrier around world's spawnpoint.
    usage: /barrier [on|off]
    permission: nerduhc.gamemaster
    permission-message: y u do that
  uhc:
    description: Command which controls current round
    usage: /uhc [start|stop|mode|reload]
    permission: nerduhc.gamemaster
    permission-message: y u do that
  freeze:
    description: Freeze players in place (toggle)
    usage: /freeze
    permission: nerduhc.gamemaster
    permission-message: y u do that
  join:
    description: Join a team.
    usage: /join [team]
    permission: nerduhc.basic
    permission-message: y u do that
  leave:
    description: Join a team.
    usage: /join [team]
    permission: nerduhc.basic
    permission-message: y u do that
  teamlist:
    description: List the current UHC teams.
    usage: /teamlist
    permission: nerduhc.basic
    permission-message: y u do that